"""
Django settings for iuhkart project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
from os import environ
from datetime import timedelta
load_dotenv('./.env')
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-)fl4jbp8qids&ut)=(a@55tw-^7&&kbhl*_5_0f!2$euge10d='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS  = ['https://3f70-2405-4802-811d-8a80-10b8-2988-6f1b-1e57.ngrok-free.app']
CORS_ORIGIN_ALLOW_ALL = True   
ALLOWED_HOSTS = ['*']


# Application definition

DEFAULT_APPS  = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.postgres'
]

THIRD_PARTY_APPS = [
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'drf_spectacular',
]

LOCAL_APPS = [
    'apps.account',
    'apps.product',
    'apps.address',
    'apps.cart',
    'apps.discount',
    'apps.review',
    'apps.order',
    'apps.dashboard'
]

INSTALLED_APPS = DEFAULT_APPS + LOCAL_APPS + THIRD_PARTY_APPS


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'iuhkart.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'iuhkart.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases
PROJECT_STATUS = environ.get('STATUS')
if PROJECT_STATUS == 'DEV':
    # DATABASES = {
    #     'default': {
    #         'ENGINE': 'django.db.backends.sqlite3',
    #         'NAME': BASE_DIR / 'db.sqlite3',
    #     }
    # }
    DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.postgresql',
                'NAME': environ['NAME'],
                'USER': environ['DBUSER'],
                'PASSWORD': environ['PASSWORD'],
                'HOST': 'localhost',
                'PORT': environ['PORT'],
            }
        }
else:
    DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.postgresql',
                'NAME': environ['NAME'],
                'USER': environ['DBUSER'],
                'PASSWORD': environ['PASSWORD'],
                'HOST': environ['HOST'],
                'PORT': environ['PORT'],
            }
        }


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

AUTH_USER_MODEL = "account.User"

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}
SPECTACULAR_SETTINGS = {
    'TITLE': 'IUHKart Snippets API',
    'DESCRIPTION': 'Swagger for IUHKart Backend API',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'SWAGGER_UI_SETTINGS': {
        'persistAuthorization': True,
    },
    'COMPONENT_SPLIT_REQUEST': True,
    'POSTPROCESSING_HOOKS': [
        'drf_spectacular.hooks.postprocess_schema_enums',
    ],
    'ENUM_NAME_OVERRIDES': {},
    'SORT_OPERATION_PARAMETERS': True,
    'DISABLE_ERRORS_AND_WARNINGS': False,
}

SIMPLE_JWT = {
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_HEADER_TYPES': ('Bearer',),
    'ACCESS_TOKEN_LIFETIME': timedelta(days=30),
}
STATIC_URL = '/static/'


# MEDIA_URL = '/media/'
# MEDIA_ROOT = BASE_DIR / 'media' 
DEFAULT_FILE_STORAGE = 'storages.backends.azure_storage.AzureStorage'
AZURE_ACCOUNT_NAME = environ.get('AZURE_ACCOUNT_NAME')
AZURE_ACCOUNT_KEY = environ.get('AZURE_ACCOUNT_KEY')
AZURE_CUSTOM_DOMAIN = f'{AZURE_ACCOUNT_NAME}.blob.core.windows.net'
DEFAULT_FILE_STORAGE = 'storages.backends.azure_storage.AzureStorage'
AZURE_CONNECTION_STRING = environ.get('AZURE_CONNECTION_STRING')

# Specify Azure storage settings
class AzureStorageSettings:
    def __init__(self):
        self.account_name = AZURE_ACCOUNT_NAME
        self.account_key = AZURE_ACCOUNT_KEY
        self.custom_domain = AZURE_CUSTOM_DOMAIN

AZURE_STORAGE_SETTINGS = AzureStorageSettings()

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'aiclub.iuh@gmail.com'
EMAIL_HOST_PASSWORD = "abc"
EMAIL_USE_TLS = True

#METABASE
METABASE_SITE_URL = environ.get('METABASE_SITE_URL')
METABASE_EMBEDDING_SECRET_KEY = environ.get('METABASE_EMBEDDING_SECRET_KEY')

#PAYOS
PAYOS_CLIENT_ID = environ.get('PAYOS_CLIENT_ID')
PAYOS_API_KEY = environ.get('PAYOS_API_KEY')
PAYOS_CHECKSUM_KEY = environ.get('PAYOS_CHECKSUM_KEY')